config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :cities
  resources :products
  resources :carts

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)

        if current_item
            current_item.quantity += 1
        else 
            current_item = line_items.build(product_id: product.id, unit_price: product.price)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def invalid_cart
      logger.error "Attempt to access an invalid cart #{params[:id]}"
      redirect_to products_index_path, notice: 'Invalid Cart'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.slim
- if notice
    div#notice = notice
    table class ="table"
        - @cart.line_items.each do |line_item|
            tr
                td = line_item.product.name
                td = line_item.quantity
           

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

=> link_to 'Show', @cart
'|
=< link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
- if notice
    div#notice = notice
table class ="table table-striped"
    thead
        tr 
            th scope ="col" Product
            th scope ="col" Quantity
            th scope ="col" Price
            th
            th

    - @cart.line_items.each do |line_item|
        tr  
            td.product-info
                => image_tag(line_item.product.image_url)
                = line_item.product.name 
            td.product-quantity 
                = line_item.quantity
            td.product-price 
                = number_to_currency(line_item.product.price)
            td.cart-actions
                a> href="/" 
                    i class="glyphicon glyphicon-trash"
            td.cart-actions
                a> href="/" 
                     i class="glyphicon glyphicon-refresh"
                
    tfoot
        tr
            td
                = link_to "Continue Shopping", products_path, class: "btn btn-default"
            td colspan= 1 Total:
            td = number_to_currency(@cart.total_price)
            td
            td
                = link_to "Checkout", products_path, class: "btn btn-success btn-lg checkout"