config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :cities
  resources :products
  resources :carts

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
    has_many :products

    validates :name, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.slim
= form_for @city do |f|
  - if @city.errors.any?
    #error_explanation
      h2 = "#{pluralize(@city.errors.count, "error")} prohibited this city from being saved:"
      ul
        - @city.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/cities/edit.html.slim
h1 Editing city

== render 'form'

=> link_to 'Show', @city
'|
=< link_to 'Back', cities_path

app/views/cities/index.html.slim
h1 Listing cities

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @cities.each do |city|
      tr
        td = city.name
        td = link_to 'Show', city
        td = link_to 'Edit', edit_city_path(city)
        td = link_to 'Destroy', city, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New City', new_city_path

app/views/cities/new.html.slim
h1 New city

== render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.slim
p#notice = notice

p
  strong Name:
  = @city.name

=> link_to 'Edit', edit_city_path(@city)
'|
=< link_to 'Back', cities_path