config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :cities
  resources :products
  resources :carts

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :city
    has_many :line_items

    before_destroy :ensure_not_referenced_by_line_item

    validates :name, presence: true
    validates :description, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|png)\Z}i,
        message: 'must be a GIF, JPG or PNG format'
    }
    validates :category, inclusion: {
        in: %w(Vegetables Meats Fish Fruits),
        message: '%{value} is not a valid category'
    }

    private

    def ensure_not_referenced_by_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
            throw :abort
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @city = City.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price, :category, :city_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.text_field :image_url
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :category
    = f.select :category, %w(Vegetables Meats Fruits Fish), prompt:'Select Category'
  .field
    = f.label :city
    = f.select :city_id, City.all.collect{|city| [city.name, city.id] }, {include_blank: 'Select City'}
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

=> link_to 'Show', @product
'|
=< link_to 'Back', products_path

app/views/products/index.html.slim
div.row
  = render 'carts/cart'
  - @products.each do |product|
    div.col-md-4.products
      div.product
        div.product-img = link_to image_tag(product.image_url), product
        div.product-details
          h3 = product.name
          div.product-price
            span.price = number_to_currency(product.price) 
            = button_to 'Add to Cart', line_items_path(product_id: product), class: "add-to-cart btn btn-primary"
    
  
      / td = link_to 'Edit', edit_product_path(product)
      / td = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Description:
  = @product.description
p
  strong Image:
  = image_tag(@product.image_url)
p
  strong Price:
  = @product.price
p
  strong Category:
  = @product.category

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path