config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :cities
  resources :products
  resources :carts

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :order, optional: true
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Item added to cart.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.slim
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      ul
        - @line_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :cart
    = f.text_field :cart
  .actions = f.submit

app/views/line_items/edit.html.slim
h1 Editing line_item

== render 'form'

=> link_to 'Show', @line_item
'|
=< link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line_items

table
  thead
    tr
      th Product
      th Cart
      th
      th
      th

  tbody
    - @line_items.each do |line_item|
      tr
        td = line_item.product
        td = line_item.cart
        td = link_to 'Show', line_item
        td = link_to 'Edit', edit_line_item_path(line_item)
        td = link_to 'Destroy', line_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line_item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong Product:
  = @line_item.product
p
  strong Cart:
  = @line_item.cart

=> link_to 'Edit', edit_line_item_path(@line_item)
'|
=< link_to 'Back', line_items_path